export const CHANGE_CHECKBOX = 'CHANGE_CHECKBOX';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const SET_SEARCH_ID = 'GET_SEARCH_ID';
export const GET_SEARCH_ID = 'GET_SEARCH_ID';
export const SET_ALL_TICKETS = 'SET_ALL_TICKETS';
export const ADD_PART_TICKETS = 'ADD_PART_TICKETS';
export const SET_NEW_PART_TICKETS = 'SET_NEW_PART_TICKETS';
